
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CORCHETEABRE = 25;
  public static final int DOSPUNTOS = 27;
  public static final int RESERVADA_PORDEFECTO = 42;
  public static final int SIGNOPOTENCIA = 28;
  public static final int SIGNOIGUALIGUAL = 17;
  public static final int CHARR = 59;
  public static final int PARENTESISCIERRA = 3;
  public static final int PUNTOYCOMA = 6;
  public static final int RESERVADA_VOID = 49;
  public static final int ENTERO = 56;
  public static final int SIGNOIGUAL = 12;
  public static final int RESERVADA_IMPRIMIR = 39;
  public static final int RESERVADA_SELECTOR = 40;
  public static final int RESERVADA_ACADENA = 52;
  public static final int RESERVADA_CORTAR = 46;
  public static final int SIGNODIVISION = 10;
  public static final int PARENTESISABRE = 2;
  public static final int RESERVADA_SI = 37;
  public static final int RESERVADA_VERDADERO = 33;
  public static final int RESERVADA_PARA = 44;
  public static final int RESERVADA_DOBLE = 31;
  public static final int RESERVADA_NUEVO = 55;
  public static final int RESERVADA_CARACTER = 35;
  public static final int SIGNOMAS = 8;
  public static final int RESERVADA_MIENTRAS = 43;
  public static final int SIGNOMENOS = 9;
  public static final int SIGNOCOMA = 18;
  public static final int SIGNOMENOR = 14;
  public static final int ID = 57;
  public static final int SIGNOPOR = 7;
  public static final int EOF = 0;
  public static final int SIGNOMAYOR = 13;
  public static final int RESERVADA_BINARIO = 32;
  public static final int RESERVADA_FALSO = 34;
  public static final int SIGNOMODULO = 11;
  public static final int SIGNOINTERROGACION = 29;
  public static final int LLAVEABRE = 4;
  public static final int error = 1;
  public static final int LLAVECIERRA = 5;
  public static final int CADENA = 58;
  public static final int RESERVADA_HACER = 45;
  public static final int RESERVADA_CASO = 41;
  public static final int RESERVADA_TIPODE = 51;
  public static final int RESERVADA_ENTERO = 30;
  public static final int SIGNOMENORIGUAL = 16;
  public static final int SIGNODIFERENTE = 19;
  public static final int DECIMALES = 60;
  public static final int SIGNOOR = 22;
  public static final int SIGNONOT = 24;
  public static final int SIGNOAND = 23;
  public static final int SIGNOINCREMENTO = 20;
  public static final int CORCHETECIERRA = 26;
  public static final int SIGNOMAYORIGUAL = 15;
  public static final int RESERVADA_LONGITUD = 53;
  public static final int RESERVADA_SINO = 38;
  public static final int SIGNODECREMENTO = 21;
  public static final int RESERVADA_CONTINUAR = 47;
  public static final int RESERVADA_REDONDEO = 50;
  public static final int RESERVADA_RETORNO = 48;
  public static final int RESERVADA_EJECUTAR = 54;
  public static final int RESERVADA_CADENA = 36;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PARENTESISABRE",
  "PARENTESISCIERRA",
  "LLAVEABRE",
  "LLAVECIERRA",
  "PUNTOYCOMA",
  "SIGNOPOR",
  "SIGNOMAS",
  "SIGNOMENOS",
  "SIGNODIVISION",
  "SIGNOMODULO",
  "SIGNOIGUAL",
  "SIGNOMAYOR",
  "SIGNOMENOR",
  "SIGNOMAYORIGUAL",
  "SIGNOMENORIGUAL",
  "SIGNOIGUALIGUAL",
  "SIGNOCOMA",
  "SIGNODIFERENTE",
  "SIGNOINCREMENTO",
  "SIGNODECREMENTO",
  "SIGNOOR",
  "SIGNOAND",
  "SIGNONOT",
  "CORCHETEABRE",
  "CORCHETECIERRA",
  "DOSPUNTOS",
  "SIGNOPOTENCIA",
  "SIGNOINTERROGACION",
  "RESERVADA_ENTERO",
  "RESERVADA_DOBLE",
  "RESERVADA_BINARIO",
  "RESERVADA_VERDADERO",
  "RESERVADA_FALSO",
  "RESERVADA_CARACTER",
  "RESERVADA_CADENA",
  "RESERVADA_SI",
  "RESERVADA_SINO",
  "RESERVADA_IMPRIMIR",
  "RESERVADA_SELECTOR",
  "RESERVADA_CASO",
  "RESERVADA_PORDEFECTO",
  "RESERVADA_MIENTRAS",
  "RESERVADA_PARA",
  "RESERVADA_HACER",
  "RESERVADA_CORTAR",
  "RESERVADA_CONTINUAR",
  "RESERVADA_RETORNO",
  "RESERVADA_VOID",
  "RESERVADA_REDONDEO",
  "RESERVADA_TIPODE",
  "RESERVADA_ACADENA",
  "RESERVADA_LONGITUD",
  "RESERVADA_EJECUTAR",
  "RESERVADA_NUEVO",
  "ENTERO",
  "ID",
  "CADENA",
  "CHARR",
  "DECIMALES"
  };
}

