
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int res_SELECTOR = 40;
  public static final int res_IMPRIMIR = 39;
  public static final int res_PORDEFECTO = 42;
  public static final int greaterequals = 15;
  public static final int CHARR = 59;
  public static final int plus = 8;
  public static final int notsign = 24;
  public static final int res_TIPODE = 51;
  public static final int mod = 11;
  public static final int res_ENTERO = 30;
  public static final int res_VOID = 49;
  public static final int ENTERO = 56;
  public static final int minus = 9;
  public static final int open_par = 2;
  public static final int res_VERDADERO = 33;
  public static final int res_BINARIO = 32;
  public static final int coma = 18;
  public static final int res_CARACTER = 35;
  public static final int res_MIENTRAS = 43;
  public static final int doublepoint = 27;
  public static final int menosmenos = 21;
  public static final int orsign = 22;
  public static final int res_PARA = 44;
  public static final int masmas = 20;
  public static final int res_DOBLE = 31;
  public static final int res_NUEVO = 55;
  public static final int ID = 57;
  public static final int brack_open = 4;
  public static final int closed_par = 3;
  public static final int EOF = 0;
  public static final int res_CADENA = 36;
  public static final int error = 1;
  public static final int diff = 19;
  public static final int res_SI = 37;
  public static final int equals = 12;
  public static final int CADENA = 58;
  public static final int times = 7;
  public static final int res_CASO = 41;
  public static final int res_FALSO = 34;
  public static final int res_HACER = 45;
  public static final int DECIMALES = 60;
  public static final int brack_close = 5;
  public static final int res_LONGITUD = 53;
  public static final int corclose = 26;
  public static final int res_RETORNO = 48;
  public static final int res_CONTINUAR = 47;
  public static final int equalsequals = 17;
  public static final int prd_cma = 6;
  public static final int greater = 13;
  public static final int res_REDONDEO = 50;
  public static final int res_CORTAR = 46;
  public static final int coropen = 25;
  public static final int res_EJECUTAR = 54;
  public static final int lesser = 14;
  public static final int res_SINO = 38;
  public static final int question = 29;
  public static final int lesserequals = 16;
  public static final int div = 10;
  public static final int res_ACADENA = 52;
  public static final int andsign = 23;
  public static final int power = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "open_par",
  "closed_par",
  "brack_open",
  "brack_close",
  "prd_cma",
  "times",
  "plus",
  "minus",
  "div",
  "mod",
  "equals",
  "greater",
  "lesser",
  "greaterequals",
  "lesserequals",
  "equalsequals",
  "coma",
  "diff",
  "masmas",
  "menosmenos",
  "orsign",
  "andsign",
  "notsign",
  "coropen",
  "corclose",
  "doublepoint",
  "power",
  "question",
  "res_ENTERO",
  "res_DOBLE",
  "res_BINARIO",
  "res_VERDADERO",
  "res_FALSO",
  "res_CARACTER",
  "res_CADENA",
  "res_SI",
  "res_SINO",
  "res_IMPRIMIR",
  "res_SELECTOR",
  "res_CASO",
  "res_PORDEFECTO",
  "res_MIENTRAS",
  "res_PARA",
  "res_HACER",
  "res_CORTAR",
  "res_CONTINUAR",
  "res_RETORNO",
  "res_VOID",
  "res_REDONDEO",
  "res_TIPODE",
  "res_ACADENA",
  "res_LONGITUD",
  "res_EJECUTAR",
  "res_NUEVO",
  "ENTERO",
  "ID",
  "CADENA",
  "CHARR",
  "DECIMALES"
  };
}

